### ISSUE TITLE
A way to compare (previously) generated files to (fresh) generated files

### ISSUE THREAD

**Issue by marks** [plopjs/plop#177]
I am using plop <3 to generate whole project folders but I'm not sure if that's even relevant here.

The problem I am trying to solve is if I update my generators with, for example, a critical bug fix, how can I quickly help users of my generator do a diff with the their previously generated code versus what would be generated if they generated it today.

Is this a problem in-scope for this project and are there any short term solutions or thoughts by the team?

Thank you in advance!

**Comment by amwmedia** [comment]
I've often thought about this issue and how it could be solved for. However, I don't see an easy path forward for building it into `plop`.

What I WILL say, is that in the past I have been able to successfully write codemods using [jscodeshift](https://github.com/facebook/jscodeshift) that target generated code. Because the generated code has consistent structure, identifying files that need to change was pretty easy.
