### ISSUE TITLE
(in)appropriate for use with creating packages?

### ISSUE THREAD

**Issue by dfee** [plopjs/plop#213]
I've got a monorepo, and I'm shopping for a tool that can create packages based on templates. Is this the wrong tool for that job?

I've been looking around for a definitive answer on the subject in these issues, but I can't find one.

My research thus far is that:
- plop handles "flat file" generation fine
- plop does not handle directory creation, or recursion.

Would you advocate I use a different tool for this?

**Comment by crutchcorn** [comment]
There's certainly nothing that would prevent you from using Plop! Because we use simple tools under-the-hood, there's nothing preventing you from going wild in your plopfile and creating directories AND recursion:

https://github.com/plopjs/plop#using-a-dynamic-actions-array

You can import files and even build CLIs on top of plop if you wanted to. Also, to say that it doesn't handle directory creation is a bit misleading. I've had many many many subfolders created and handled by plop just fine.

It sounds like it'd fit your bill, but what specific behavior are you looking for that you fear might not be present?
