### ISSUE TITLE
You can not bypass conditional prompts: method，For emergency help

### ISSUE THREAD

**Issue by mybraveheart** [plopjs/plop#226]
For emergency help, when I want to input all instructions to generate a template at once through the node exec instruction, the console outputs [error] you can not bypass conditional prompts: method, Because 'when' is added to the middle instruction, but everything is normal when 'when' returns true. Because node does not support the middle interaction process, can I add an attribute, let me skip this error and continue to execute the later instruction. Thank you very much.

**Comment by mybraveheart** [comment]
help

**Comment by amwmedia** [comment]
When I was implementing the `bypass` feature I couldn't think of a good way to ensure that plop would know how to handle prompts properly when `when` functions were in use. This is because the bypass feature does not "automate" the prompts that inquirer presents, rather it skips those prompts because we already have a value to use. I'd love if someone could think up a good strategy for how to do this better, but for now it is a limitation of the bypass feature. You can bypass up to the first use of a `when` function, but not past that point.
