### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by bung87** [plopjs/plop#251]
Am writing a cli tool in `typescript`, provide feature like `yeoman`'s `generator-node` does, I use to write a tool do health checks on existed project, now I want write a scaffolding tool , my previous experience write a custom runner use `pirates`,`livescript` and `child_process.fork` , I wonder to know if there's handy tool for this kind of task. if `plop` repository contains unit tests that would be wonderful

you can check current process here https://github.com/bung87/psalm

**Comment by crutchcorn** [comment]
Unit tests are certainly something that we've been wanting to have for some time, but simply don't have setup yet. 

The way we see it, we'd like to focus on user experience itself, rather than testing internals. As such, we'd probably want to use `child_process` or something along those lines

If this is something you'd be willing to contribute we'd deeply appreciate it! Even if it's just a framework to create tests with a single example, I could jump in and write more tests once we have things running

**Comment by crutchcorn** [comment]
Initial work has been merged into `master` (soon to be renamed to `main`).
