### ISSUE TITLE
how to use plop from code

### ISSUE THREAD

**Issue by paulfrench** [plopjs/plop#327]
I'm writing a VSCode extension that will generate code from a spec of some sort. I want to use plop to do the code gen but I cannot see a way to execute plop from code. The example in the README.md in this project still loads a plopfile.js which is not possible from an extension since the extension is bundled as a single file. Can you supply a simple code example to run plop using pure javascript (or typescript) without the need to load a plopfile.js?

Many thanks

**Comment by crutchcorn** [comment]
@paulfrench in order to run `node-plop` without `plop` CLI itself, you can actually read through the `plop` source code to see how it's done:

https://github.com/plopjs/plop/blob/master/packages/plop/src/plop.js#L123-L176 

We also need to work on improving `node-plop` documentation, but that's a separate issue soon to come
