### ISSUE TITLE
v3 Undocumented Change to titleCase hbs helper

### ISSUE THREAD

**Issue by garrettmorse** [plopjs/plop#348]
## The problem
In Plop v2, the titlecase handlebars helper behaves as follows:

`value: garrett-was-here`

`{{ titleCase value }}` ==> `Garrett Was Here`

In Plop v3, the titlecase handlebars helper behaves as follows:

`value: garrett-was-here`

`{{ titleCase value }}` ==> `Garrett-Was-Here`

## Minimal Repro

See my stackblitz environment here => https://stackblitz.com/edit/node-yea9rd?file=index.js

Plop v3 is installed there currently. You can run the Plop CLI with `node index.js`.

---

Was this an intended change by the Plop team? I just want to confirm. Thanks! :) <3

**Comment by crutchcorn** [comment]
You're 100% right, this was both an undocumented and unintended change! 

This was caused by a dependency migration that I thought was transitive, but clearly wasn't:

https://github.com/plopjs/node-plop/compare/v0.26.3...v0.30.0#diff-e36453fba1ad56a85b195753d9c03d4d3864f84832d2c1f2b4e7b2362b0d2604R15

I'll make a bug fix tonight, probably under the `3.1` label

**Comment by crutchcorn** [comment]
Actually, taking another look at this, this behavior is expected. I think the 2.0 behavior was incorrect and the dep upgrade just "fixed" the behavior. I'll update the 3.0 CHANGELOG and RELEASE documentation to make this more explicit

Thanks for raising this!

**Comment by garrettmorse** [comment]
Thanks!
